/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {Movie} from '../../models/movie';

export interface AddMovie$Params {
  movieId: string;
}

export function addMovie(http: HttpClient, rootUrl: string, params: AddMovie$Params, context?: HttpContext): Observable<StrictHttpResponse<Movie>> {
  const rb = new RequestBuilder(rootUrl, addMovie.PATH, 'post');
  if (params) {
    rb.query('movieId', params.movieId, {});
  }

  return http.request(
    rb.build({responseType: 'json', accept: '*/*', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Movie>;
    })
  );
}

addMovie.PATH = '/api/v1/movies/admin/add';
