/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {Movie} from '../../models/movie';

export interface GetAllMovies$Params {
}

export function getAllMovies(http: HttpClient, rootUrl: string, params?: GetAllMovies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Movie>>> {
  const rb = new RequestBuilder(rootUrl, getAllMovies.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({responseType: 'json', accept: '*/*', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Movie>>;
    })
  );
}

getAllMovies.PATH = '/api/v1/movies';
