/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {Movie} from '../../models/movie';

export interface RateMovie$Params {
  id: number;
  userEmail: string;
  rate: number;
}

export function rateMovie(http: HttpClient, rootUrl: string, params: RateMovie$Params, context?: HttpContext): Observable<StrictHttpResponse<Movie>> {
  const rb = new RequestBuilder(rootUrl, rateMovie.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('userEmail', params.userEmail, {});
    rb.query('rate', params.rate, {});
  }

  return http.request(
    rb.build({responseType: 'json', accept: '*/*', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Movie>;
    })
  );
}

rateMovie.PATH = '/api/v1/movies/{id}/rate';
