/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthenticationRequest } from './models/authentication-request';
export { AuthenticationResponse } from './models/authentication-response';
export { Movie } from './models/movie';
export { PageableObject } from './models/pageable-object';
export { PageMovie } from './models/page-movie';
export { Rating } from './models/rating';
export { RegistrationRequest } from './models/registration-request';
export { SortObject } from './models/sort-object';
